"""World 1 - "The Silence": the FICTION of each escape mechanism.

Phase F §10.1. `escape.MECHANISMS` keeps the grammar (family, discovery
logic, placement, RNG order); this file holds what a `power_station` /
`radio_tower` / ... looks, sounds and reads like in a temperate valley.
The engine reads it via `game.world.mechanism_prose`; a world that
omits an entry gets `escape._FALLBACK_PROSE`.

Every string here is verbatim from the pre-Phase-F `escape.MECHANISMS`.
"""

MECHANISM_PROSE = {
    "mountain_pass": {
        "name": "the old mountain pass",
        "closed": "The road out of the valley is choked with abandoned vehicles, bumper to bumper for miles. Nothing is driving out that way.",
        "route": "There's an old foot pass over the ridge - the ranger maps still show it.",
        "obstacle": "The pass trailhead is behind a locked forestry gate.",
        "require": "A ranger station keeps the forestry gate keys.",
        "item": "forestry gate key",
        "obstacle_desc": "A locked forestry service gate blocks the trail up to the pass.",
        "escape_desc": "The foot pass switchbacks up over the ridge and down the far side. This is the way out.",
        "roles": {"closed": "the clogged highway", "route": "a trailhead noticeboard",
                  "obstacle": "forestry gate", "require": "the ranger station"},
        "landmark": "A notch in the ridgeline shows where a footpath climbs out over the valley wall",
    },
    "rail_tunnel": {
        "name": "the railway tunnel",
        "closed": "The main bridge over the river is down - dropped into the water, deliberately by the look of the charges still wired to what's left.",
        "route": "The rail line runs through a tunnel in the eastern hills - it comes out beyond the river entirely.",
        "obstacle": "The tunnel mouth is caved in. Not impassable, but not walkable either without clearing it.",
        "require": "The rail maintenance depot had the tools for exactly this.",
        "item": "rail clearing charge",
        "obstacle_desc": "The railway tunnel entrance is half-collapsed. You'd need something to clear the fall.",
        "escape_desc": "Past the fall the tunnel runs straight and level, a cold draught coming the other way. Daylight, far ahead.",
        "roles": {"closed": "the wrecked bridge", "route": "the rail yard",
                  "obstacle": "collapsed tunnel", "require": "the rail maintenance depot"},
        "landmark": "A railway embankment runs dead straight toward a cutting in the hills",
    },
    "service_route": {
        "name": "the dam service road",
        "closed": "The reservoir has come up over the valley road. It's a lake now, not a road.",
        "route": "There's a service road along the downstream face of the dam that stays above the water line.",
        "obstacle": "The service road is closed by a gate at the dam end.",
        "require": "The gate key is kept in the dam control room.",
        "item": "service gate key",
        "obstacle_desc": "A chained and padlocked service gate blocks the road along the dam.",
        "escape_desc": "The service road runs on past the gate, climbing away from the water and out of the valley.",
        "roles": {"closed": "the flooded road", "route": "the dam",
                  "obstacle": "service gate", "require": "the dam control room"},
        "landmark": "A concrete dam wall stands across the head of the valley, a service road switchbacking up its face",
    },
    "boat_crossing": {
        "name": "the boat crossing",
        "closed": "Every road inland is blocked - checkpoints, wrecks, one of them still burning.",
        "route": "The marina still has boats in their slips. Water doesn't have checkpoints.",
        "obstacle": "The boats are dry - no fuel in any of the tanks.",
        "require": "The harbourmaster's shed stores fuel drums.",
        "item": "jerrycan of fuel",
        "obstacle_desc": "A serviceable boat sits ready at the dock, but the fuel gauge reads empty.",
        "escape_desc": "The engine catches. You take the boat out past the harbour wall and open water opens up ahead.",
        "roles": {"closed": "the blocked checkpoint", "route": "the marina",
                  "obstacle": "empty boat", "require": "the harbourmaster's shed"},
        "landmark": "Masts and a marina breakwater stand out along the waterfront",
    },
    "evac_corridor": {
        "name": "the evacuation corridor",
        "closed": "The interstate on-ramp is collapsed - a whole overpass down across all the lanes.",
        "route": "There was a signed evacuation corridor on the surface streets, running north out of town.",
        "obstacle": "The corridor is barricaded where it leaves the built-up area - a checkpoint that was never taken down.",
        "require": "The police station has the corridor's access codes and the barricade key.",
        "item": "barricade key",
        "obstacle_desc": "A military barricade closes the evacuation corridor - concrete, wire, and a locked vehicle gate.",
        "escape_desc": "Past the barricade the corridor runs clear and straight, the evac signs still up, pointing you out.",
        "roles": {"closed": "a collapsed overpass", "route": "an evacuation-route sign",
                  "obstacle": "barricade", "require": "the police station"},
        "landmark": "A tall evacuation-route sign still stands over the road, its reflectors catching the light",
    },
    "power_station": {
        "name": "the road tunnel",
        "closed": "Every road out ends the same way - a slide, a checkpoint, a bridge dropped in the river. Nothing is driving out.",
        "route": "There's a road tunnel bored straight through the ridge - it comes out on the far side of the mountains.",
        "obstacle": "The tunnel is closed by a heavy electric gate, and the gate is dead. No power, no way to raise it.",
        "require": "Fuel drums are stored at the highway works yard.",
        "item": "jerrycan of fuel",
        "obstacle_desc": "A heavy electric vehicle gate seals the tunnel mouth. The control panel is unlit.",
        "escape_desc": "The gate grinds up. The tunnel runs level and straight through the ridge, and there is light at the far end.",
        "roles": {"closed": "a blocked checkpoint", "route": "the tunnel mouth",
                  "obstacle": "the tunnel gate", "require": "the works yard",
                  "power": "the hydro station"},
        "power_fact": "The tunnel gate's power comes from the hydro station downriver.",
        "power_obstacle_ev": "The gate is electric and its panel is stone dead. A cable run leaves it heading downriver - the power comes from somewhere else.",
        "power_site_ev": "A heavy cable leaves the switch room here, strung on poles toward the ridge tunnel.",
        "generator_ev": "The generator's fuel gauge sits on empty. It will not turn over dry.",
        "power_restored_desc": "The generator catches and runs. Downriver, the tunnel gate's panel lights up.",
        "landmark": "A dark tunnel portal is bored into the hillside, lane markings running straight in",
    },
    "dam_valves": {
        "name": "the lower valley road",
        "closed": "The main road out is gone - a whole hillside came down across it.",
        "route": "There's a lower road that runs under the dam and out through the far end of the valley. It's still there, under the water.",
        "obstacle": "The lower road is under the reservoir. The water level is held by the dam and set from the control room.",
        "require": "The dam control room holds the gates for the whole reservoir - a bank of controls.",
        "item": None,
        "obstacle_desc": "The lower road runs straight down into the reservoir. Too deep to wade.",
        "escape_desc": "The water's dropped off the lower road. It runs on out through the end of the valley, wet but clear.",
        "roles": {"closed": "the landslide", "route": "the lower road",
                  "obstacle": "the flooded road", "require": "the dam control room"},
        "controls": ["the main sluice", "the east intake", "the west intake"],
        "obvious_control": "the main sluice",
        "controls_prompt": "One of them sets the valley reservoir - but which?",
        "controls_lore": "governs the valley reservoir",
        "control_wrong_obvious": "Water roars away downstream - but the level behind the dam doesn't move. The main sluice feeds the river below, not the valley reservoir.",
        "control_wrong_other": "The gate grinds open. The reservoir drops a hand's width, then holds. This one only takes part of it.",
        "control_correct": "The gate opens and stays open. Behind the dam the reservoir starts falling in earnest - and out on the lower road, the water pulls back off the tarmac.",
        "landmark": "The land falls away where a road cuts down and out of the lower valley",
    },
    "radio_tower": {
        "name": "the emergency access road",
        "closed": "Every road out ends the same way - a checkpoint, a slide, a bridge dropped in the river. Nothing is driving out.",
        "route": "An emergency broadcast log, left open on the desk. The valley's channel is still monitored from the regional station - the last entry reads: 'if the tower comes back up, we can talk someone out.'",
        "obstacle": "The broadcast tower stands on the ridge, and the transmitter is dark. The control panel is dead - no power to it at all.",
        "require": "A fuel cache is kept at the ranger depot.",
        "item": "jerrycan of fuel",
        "obstacle_desc": "The transmitter housing at the tower base is silent, its panel unlit.",
        "escape_desc": "The emergency access road climbs the ridge exactly where the voice said it would, and drops away down the far side. This is the way out.",
        "roles": {"closed": "a dropped bridge", "route": "the broadcast log",
                  "obstacle": "the broadcast tower", "require": "the ranger depot",
                  "power": "the generator shed"},
        "power_fact": "The valley can still be reached from outside - but only if the broadcast tower is transmitting.",
        "power_obstacle_ev": "The transmitter is dead. A conduit runs from it down the slope toward a shed - the power comes from there, and nothing is coming through.",
        "power_site_ev": "A generator sits in the shed, cabled up the slope to the tower. This is what drives the transmitter.",
        "generator_ev": "The generator's tank is bone dry. It will not turn over without fuel.",
        "power_restored_desc": "The generator catches. Up on the ridge the transmitter's panel lights, and the channel opens with a hiss of static.",
        "f_obstacle": "There is no way out to be seen - not until the tower is transmitting and someone on the outside answers.",
        "d_route": "The way out isn't a road you can find on your own - it's whatever the people on the other end of that channel tell you.",
        "route_reveal_ev": "The channel crackles, then a voice - clear, close. They read you an emergency access road up the {bearing} ridge, a track that was never on any map. It's marked for you now.",
        "landmark": "A lattice radio mast rises above the treeline, red lamps still blinking at the top",
    },
    "airfield_plane": {
        "name": "the airstrip",
        "closed": "Every road out ends the same way - a checkpoint, a slide, a bridge dropped in the river. Nothing is driving out.",
        "route": "A crop-duster sits tied down on a grass strip where the valley opens up. Small - barely two seats - but it flies, and the strip runs right to where the ridge drops away.",
        "obstacle": "The plane won't start. The propeller is off the shaft entirely, and both fuel gauges read empty.",
        "require": "The propeller is racked on the wall of the hangar by the strip, wrapped in a blanket.",
        "item": "propeller",
        "require2": "A drum of avgas and a hand pump stand in the field store at the edge of the strip.",
        "item2": "can of avgas",
        "obstacle_desc": "The crop-duster is airworthy but grounded - no propeller fitted, no fuel in the tanks.",
        "escape_desc": "The prop's on and the tanks are full. The engine turns over twice and catches. You taxi to the end of the strip, open the throttle, and lift off over the ridge. This is the way out.",
        "roles": {"closed": "the blocked checkpoint", "route": "the airstrip",
                  "obstacle": "the grounded plane", "require": "the hangar",
                  "require2": "the field store"},
        "assemble_desc": "You wrestle the propeller onto the shaft and pin it, then pump both tanks full from the drum. The engine catches on the second turn - it's ready to fly.",
        "landmark": "A windsock and a long flat airstrip open out past a chain-link fence",
    },
    "tidal_causeway": {
        "name": "the tidal causeway",
        "closed": "Every road inland is blocked - checkpoints, a slide, a bridge dropped in the river. Nothing is driving out.",
        "route": "A stone causeway runs out from the shore to a headland, and a footbridge carries on from there - off the valley entirely, inland. But the causeway is tidal: it floods at high water.",
        "obstacle": "The causeway is walkable right now, at low tide. When the water turns it goes under - chest-deep and climbing, no crossing it then.",
        "require": "A tide board is posted at the shore station - the schedule, if you read it properly.",
        "item": None,
        "require_fact": "The tide runs on a schedule you can read and plan around - a short window now, another after dark.",
        "require_ev": "The tide board: low water now, but the window is short. Miss it and the next low tide isn't until well after dark.",
        "obstacle_desc": "The causeway stretches out across the flats, wet stone, weed on the low rocks - the tide line is halfway up the marker posts already.",
        "escape_desc": "You cross the causeway at a jog, water pushing at your boots by the far end, and climb onto the headland. The footbridge runs on inland from here. You're out.",
        "roles": {"closed": "the blocked checkpoint", "route": "the shore station",
                  "obstacle": "the causeway", "require": "the tide board"},
        "landmark": "A stone causeway runs out low across the tidal flats toward a squat shore station",
    },
}
